backend:
#  name: git-gateway
#  branch: master
  name: contentful
  api_key: fs9TE1Zfprg8NL3KrO0TeP0QcqTZeqWQZd4ZU9NOaVk
  space_id: wo7a9bdetm38
  environment: master # Možete promeniti ako želite koristiti drugo okruženje

media_folder: static/images
public_folder: ../../static/images

collections:
  - name: "travel-packages"
    preview: false
    label: "Travel Packages"
    folder: "content/travel-packages"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Location", name: "location", widget: "string" }
      - { label: "Travel Date", name: "travel-date", widget: "string" }
      - { label: "Featured Image", name: "featured-image", widget: "image" }
      - { label: "Body", name: "body", widget: "markdown" }


  - name: "pesme"
    preview: false
    label: "Pesme"
    folder: "content/pesme"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Naslov", name: "title", widget: "string" }
      - { label: "Datum", name: "datum", widget: "date", format: "D.M.YYYY." }
      - { label: "Objavljeno", name: "objavljeno", widget: "string", required: false }
      - { label: "Body", name: "body", widget: "text" }
